version: '3.8'

services:
  backend:
    build: .
    container_name: backend_app
    ports:
      - "5001:5001"  
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
