"""modifiy

Revision ID: 165e8147b025
Revises: 3ce555f0ea9b
Create Date: 2025-03-07 17:13:14.659824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '165e8147b025'
down_revision: Union[str, None] = '3ce555f0ea9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_users', 'deleted_at')
    # ### end Alembic commands ###
