"""modifiy

Revision ID: 3ce555f0ea9b
Revises: 7013df86bd54
Create Date: 2025-03-07 17:11:20.121601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3ce555f0ea9b'
down_revision: Union[str, None] = '7013df86bd54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_users', 'deleted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_users', sa.Column('deleted_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
