"""modifiy

Revision ID: 7013df86bd54
Revises: a0de973a4aac
Create Date: 2025-03-07 17:07:26.444394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7013df86bd54'
down_revision: Union[str, None] = 'a0de973a4aac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_pdf_dataset', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_pdf_dataset', 'deleted_at')
    # ### end Alembic commands ###
