"""modifiy

Revision ID: a0de973a4aac
Revises: 81c145ff36b6
Create Date: 2025-03-07 17:06:17.863927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a0de973a4aac'
down_revision: Union[str, None] = '81c145ff36b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_pdf_dataset', 'deleted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_pdf_dataset', sa.Column('deleted_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
